export const imageLink = {
  tshirtBG: require("../assets/images/tshirt/backgroundTshirt.png"),
  tshirtFront: require("../assets/images/tshirt/HOCKEY_JERSEY_EDGE.png"),
  tshirtBack: require("../assets/images/tshirt/BACK_HOCKEY_JERSEY_EDGE.png"),
  chestStrip: require("../assets/images/tshirt/chestStrip.png"),
  plainShirt: require("../assets/images/template/plainShirt.png"),
  midCuff: require("../assets/images/template/midCuff.png"),
  shortCuff1: require("../assets/images/template/shortCuff1.png"),
  thinCuff: require("../assets/images/template/thinCuff.png"),
  shortCuff2: require("../assets/images/template/shortCuff2.png"),
  twoToneSleeves: require("../assets/images/template/twoToneSleeves.png"),
  none: require("../assets/images/chestStriping/none.png"),
  single2: require("../assets/images/chestStriping/single2.png"),
  triple1: require("../assets/images/chestStriping/triple1.png"),
  single1: require("../assets/images/chestStriping/single1.png"),
  double1: require("../assets/images/chestStriping/double1.png"),
  triple2: require("../assets/images/chestStriping/triple2.png"),
  tshirtCardBG: require('../assets/images/rosterCardBG.png'),

  // menu
  template: require("../assets/images/menu/template.png"),
  chestStripping: require("../assets/images/menu/chestStripping.png"),
  frontCrest: require("../assets/images/menu/frontCrest.png"),
  sleeveNumbers: require("../assets/images/menu/sleeveNumbers.png"),
  sleeveStriping: require("../assets/images/menu/sleeveStriping.png"),
  shoulderYoke: require("../assets/images/menu/shoulderYoke.png"),
  shoulderPatch: require("../assets/images/menu/shoulderPatch.png"),
  backNumbers: require("../assets/images/menu/backNumbers.png"),
  waistStriping: require("../assets/images/menu/waistStriping.png"),
  collar: require("../assets/images/menu/collar.png"),
  otherPatches: require("../assets/images/menu/otherPatches.png"),
  nameBar: require("../assets/images/menu/nameBar.png"),

  
  //   pattern
  felt: require("../assets/images/pattern/felt.png"),
  hexagonsDark: require("../assets/images/pattern/hexagonsDark.png"),
  hexagonsLight: require("../assets/images/pattern/hexagonsLight.png"),
  pride1: require("../assets/images/pattern/pride1.png"),
  pride2: require("../assets/images/pattern/pride2.png"),
  patternNone: require("../assets/images/pattern/patternNone.png"),
};
export const iconLink = {
  handBag: require("../assets/images/icon/handBag.png"),
  reload: require("../assets/images/icon/reload.png"),
  file: require("../assets/images/icon/file.png"),
  leftIcon: require("../assets/images/icon/leftIcon.png"),
  adjust: require("../assets/images/icon/adjust.png"),
  appstore: require("../assets/images/icon/appstore.png"),
  sideMenu: require("../assets/images/icon/sideMenu.png"),
  setting: require("../assets/images/icon/setting.png"),
  gallery: require("../assets/images/icon/gallery.png"),
  patternFile: require("../assets/images/icon/patternFile.png"),
  arrow_y: require("../assets/images/icon/arrow_y.png"),
  arrow_z: require("../assets/images/icon/arrow_z.png"),
  csv: require("../assets/images/icon/csv.png"),
  vector: require("../assets/images/icon/vector.png"),
};
